config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  root to: "home#index"

  get "bad_request"=>"home#bad_request"
  get "forbidden" => "home#forbidden"
  get "internal_server_error" => "home#internal_server_error"

  resources :users do
    resources :articles,only: [:index]
  end

  resources :teams do
    resources :users, only: [:index]
  end

  resources :teams do
    resources :articles, only: [:index]
  end


  resources :articles
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord

  has_many :articles,dependent: :destroy

  belongs_to :team,class_name: "Team",foreign_key: "team_id"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # deveise(gem)で使う機能
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image #プロフィール画像

  validates :username, presence: true #ユーザー名空白禁止
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :login_required #ログインが必要
  def index
    if params[:team_id] #チームに関連するユーザーを取得
      @team=Team.find(params[:team_id])
      @users=@team.users
    else
      @users=User.all #全ユーザーを取得
    end
  end

  def show
    @user=User.find(params[:id])
  end

  def edit
    @user=User.find(params[:id])

  end

  def update
    @user=User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username,:team_id,:email,:profile,:profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- ユーザー編集画面 -->
<%= form_with model: @user do |f| %>
    <div class="user-container">
            <!-- profile画像編集 -->
        <div class="field">
            <p><%= f.label :profile_image %>
            <p><%= attachment_image_tag @user,:profile_image,fallback: "baseball_st5.jpg",size:"200x200" %></p>
            <%= f.attachment_field :profile_image %></p>
        </div>
            <!-- ユーザー名編集 -->
        <div class="field">
            <p><%= f.label :username %>
            <%= f.text_field :username %></p>
        </div>
            <!-- eメールアドレス編集 -->
        <div class="field">
            <p><%= f.label :email %>
            <%= f.email_field :email %></p>
        </div>
            <!-- profile -->
        <div class="field">
            <p><%= f.label :profile %></p>
            <p><%= f.text_area :profile,rows: 10, cols: 45 %></p>
        </div>
            <!-- 送信ボタン -->
        <div class="field">
            <%= f.submit %>
        </div>
    </div>
<% end %>

app/views/users/index.html.erb
<div class="users">
    <h2 style="font-size:4vmin;">ユーザー一覧</h2>
    <div class="flex" >
            <!-- ユーザー一覧 -->
            <% @users.each do |user| %>
                <div class="one-user">
                    <p>
                        <%= link_to user_path(user) do%> <%# ユーザー詳細ページへ %>
                            <%= attachment_image_tag user,:profile_image,fallback: "baseball_st5.jpg" %>
                        <% end %>
                    </p>
                    <p>
                        <%= link_to user_path(user) do%> <%# ユーザー詳細ページへ %>
                            <%= user.username %>
                        <% end %>
                    </p>
                </div>
            <% end %>
    </div>
</div>

app/views/users/show.html.erb
<!-- ユーザー詳細画面 -->
<div class="user-container">
    <div class="user-profile">
        <div class="field">
            <p style="font-size:5vmin;"><%= @user.username %>さんのプロフィール画面</p>
        </div>
        <div class="field">
           <!-- profile画像表示 -->
            <p><%= attachment_image_tag @user,:profile_image,fallback: "baseball_st5.jpg",size:"200x200" %></p>
        </div>
        <div class="field">
            <!-- ユーザー名表示 -->
            <p><span style="padding-right:3vmin;">名前</span><%= @user.username %></p>
        </div>
        <div class="field">
            <% if @user.id==current_user.id %>
            <!-- ユーザーeメールアドレス表示 -->
                <p><span style="padding-right:3vmin;">メールアドレス</span><%= @user.email %></p>
            <% end %>
        </div>
        <div class="field">
            <!-- ユーザーprofile文 -->
            <p style="margin-bottom:3vmin;">自己紹介</p>
            <p><%= @user.profile %></p>
        </div>
        <div class="field">
            <% if @user.id==current_user.id %>
            <!-- 閲覧しているユーザーがログインしているユーザーと同じなら編集リンクを表示 -->
                <p><%= link_to "編集",edit_user_path(@user) %></p>
            <% end %>
        </div>
        <div class="field">
            <!-- 詳細画面に表示されているユーザーの書いた記事一覧へ -->
            <%= link_to "記事一覧へ",user_articles_path(@user) %>
        </div>
    </div>
</div>
