config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  root to: "home#index"

  get "bad_request"=>"home#bad_request"
  get "forbidden" => "home#forbidden"
  get "internal_server_error" => "home#internal_server_error"

  resources :users do
    resources :articles,only: [:index]
  end

  resources :teams do
    resources :users, only: [:index]
  end

  resources :teams do
    resources :articles, only: [:index]
  end


  resources :articles
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ba1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <div class="container">
      <header>
        <div class="header_logo">
          <h1>Baseball commentator</h1>
        </div>
      </header>
      <main>
        <!-- メニューバーエリア(右上の三本線)-->
        <div class="fix">
          <!-- ユーザーログイン時 -->
          <% if user_signed_in? %>
          <div class="menu-bar">
            <!-- fontawesome -->
            <i class="fas fa-bars header_icon"></i>
            <!-- メニュー欄 -->
            <aside class="sidebar-menu">
              <div class="sidebar-menu_inner">
                <h2 class="sidebar-menu_ttl">Menu</h2>
                <i class="fas fa-times-circle sidebar-menu_icon"></i>
              </div>
              <p class="sidebar-menu_txt"><%= link_to "ホーム",root_path %></p>
              <p class="sidebar-menu_txt"><%= link_to "profile",user_path(current_user) %></p>
              <p class="sidebar-menu_txt"><%= link_to "記事の作成",new_article_path(current_user) %></p>
              <p class="sidebar-menu_txt"><%= link_to "記事一覧",articles_path %></p>
              <p class="sidebar-menu_txt"><select name="select" onChange="location.href=value;" >
                <option value="#">球団の記事を選択</option>
                <option value="/articles">全ての記事</option>
                <option value="/teams/1/articles">中日</option>
                <option value="/teams/2/articles">阪神</option>
                <option value="/teams/3/articles">巨人</option>
                <option value="/teams/4/articles">広島</option>
                <option value="/teams/5/articles">ヤクルト</option>
                <option value="/teams/6/articles">横浜</option>
                <option value="/teams/7/articles">ソフトバンク</option>
                <option value="/teams/8/articles">楽天</option>
                <option value="/teams/9/articles">オリックス</option>
                <option value="/teams/10/articles">ロッテ</option>
                <option value="/teams/11/articles">日本ハム</option>
                <option value="/teams/12/articles">西武</option>
              </select></p>
              <p class="sidebar-menu_txt"><%= link_to "ログアウト",destroy_user_session_path,method: :delete %></p>
              
            </aside>
            <div class="sidebar-menu-bg"></div>
          </div>
          <!-- ユーザーnotログイン時 -->
          <% else %>
            <div class="not-login-status">
              <%= link_to "新規登録",new_user_registration_path %>
              <%= link_to "ログイン" ,new_user_session_path%>
            </div>
          <% end %>
        </div>
        <%= yield %>
      </main>
      <footer>
        <p>© 2020 Kazuki</p>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= stylesheet_link_tag "application",media: "all" %>
</head>
<body>
    <div id="container">
        <header>
            <nav class="menubar">
                <a href="/">TOP</a>
            </nav>
        </header>
        <main>
            <%= yield %>
        </main>
    </div>
</body>
</html>